# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4378021a189bcb78e50c8c6c832f57c00ff202ca111b9adf04dcab02de15b51a58a0f3c4fe23c0fae4ae16498de9abc170cf26e80fe6657c5484f80259053bfb

test:
  secret_key_base: 95a0fec0615198b141123efdb0e047267d9405fdf6b8a63c07caf8bd8890e2e1b70025495f9dde2751fa5de6145774b40f74d73a9404560a0d89bda481e58304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
